OSJP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings






urlpatterns = [
    path('admin/', admin.site.urls),
    #add namespace = "" to the next line
    path('', include('scientificJournalism.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scientificJournalism/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path("", views.mainpage, name='mainpage'),
    path("login", views.logging_in, name="logging_in"),
    path("logout", views.logout, name="logout"),
    path('register', views.register, name='register'),
    path("registering", views.registering, name="registering"),
    path("activation", views.activation, name="activation"),
    path("writer", views.writer_homepage, name="writer_homepage"),
    path("new article", views.new_article, name="new_article"),
    path("submit article", views.submit_article, name="submit_article"),
    path("my articles", views.my_articles, name="my_articles"),
    path("subscribe", views.subscribe, name="subscribe"),
    path("subscribing", views.subscribing, name="subscribing"),
    path("subscriber", views.subscriber_homepage, name="subscriber_homepage"),
    path("ajax/rate", views.rating_article, name="rating_article"),
    path("ajax/comment", views.commenting_article, name="commenting_article"),
    path("article/<int:article_ID>", views.show_article, name="show_article"),
    path("archived_article/<int:article_ID>", views.show_archived_article, name="show_archived_article"),
    path("article/<field>/", views.get_field_articles, name="get_field_articles"),
    path("article/archive/<field>/", views.get_archived_field_articles, name="get_archived_field_articles"),
    path("buy article/<int:article_ID>", views.buy_article, name="buy_article"), 
    path("online_search", views.online_search, name="online_search"),  
    path("archive_search", views.archive_search, name="archive_search"),  
    path("change_lang/<lang>/", views.change_lang, name='change_lang'),
    path("archive", views.archive, name='archive'),
    
    path("EIC homepage", views.EIC_homepage, name='EIC_homepage'),
    path("just_accept_article/<int:article_ID>", views.just_accept_article, name='just_accept_article'),
    path("accept_article_in_details", views.accept_article_in_details, name='accept_article_in_details'),
    path("reject_article", views.reject_article, name='reject_article'),
    path("assign_article", views.assign_article, name='assign_article'),
    path("grap_article/<int:article_ID>", views.grap_article, name='grap_article'),
    path("show_EIC_article/<int:article_ID>", views.show_EIC_article, name='show_EIC_article'),
    path("show_new_EIC_article/<int:article_ID>", views.show_new_EIC_article, name='show_new_EIC_article'),
 

    path("AE homepage", views.AE_homepage, name='AE_homepage'),
    path("AE_apologize/<int:article_ID>", views.AE_apologize, name='AE_apologize'),
    path("show_new_AE_article/<int:article_ID>", views.show_new_AE_article, name='show_new_AE_article'),
    path("invite_reviewer", views.invite_reviewer, name='invite_reviewer'),
    path('comment_article_as_AE', views.comment_article_as_AE, name='comment_article_as_AE'),
    path("grap_reviewer_article/<int:article_ID>", views.grap_reviewer_article, name='grap_reviewer_article'),
    path("show_AE_article/<int:article_ID>", views.show_AE_article, name='show_AE_article'),



    path("reviewer homepage", views.reviewer_homepage, name='reviewer_homepage'),
    path("show_new_reviewer_article/<int:article_ID>", views.show_new_reviewer_article, name='show_new_reviewer_article'),
    path("reviewer_apologize/<int:article_ID>", views.reviewer_apologize, name='reviewer_apologize'),
    path('comment_article_as_reviewer', views.comment_article_as_reviewer, name='comment_article_as_reviewer'),

    path('admin/statistics/', views.view_statistics, name='statistics'),
 
]

scientificJournalism/models.py
from django.db import models
from django.urls import reverse
from passlib.hash import pbkdf2_sha256
from django.core.validators import FileExtensionValidator


GENDER_EN = (
    ('MALE','male'),
    ('FEMALE','female')
)

GENDER_AR = (
    ('MALE','ذكر'),
    ('FEMALE','أنثى')
)

ACCOUNT_STATUS_EN = (
    ('ONLINE','online'),
    ('FREEZE','freeze')
)

ACCOUNT_STATUS_AR = (
    ('ONLINE','نشط'),
    ('FREEZE','مجمد')
)

PACKAGE_STATUS_EN = (
    ('ACTIVE','active'),
    ('INACTIVE','inactive'),
    # ('FREEZE','freeze'),
)

PACKAGE_STATUS_AR = (
    ('ACTIVE','نشط'),
    ('INACTIVE','غير نشط'),
    # ('FREEZE','مجمد'),
)

SUBSCRIPTION_STATUS_EN = (
    ('ACTIVE','active'),
    ('INACTIVE','inactive'),
)

SUBSCRIPTION_STATUS_AR = (
    ('ACTIVE','نشط'),
    ('INACTIVE','غير نشط'),
)

ARTICLE_STATUS_EN = (
    ('REJECTED', 'rejected'),
    ('SUBMITTED','submitted'),
    ('ASSIGNED','assigned'),
    ('REVIEWED','reviewed'),
    ('FINAL_REVIEWED','final_reviewed'),
    ('WITH_REVIEWER','with reviewer'),
    # ('APOLOGIZED','apologized'),
    ('ONLINE','online'),
    ('EDITORIAL','editorial'),
    ('ARCHIVED','archived'),
)

ARTICLE_STATUS_AR = (
    ('REJECTED', 'مرفوض'),
    ('SUBMITTED','عند رئيس التحرير'),
    ('ASSIGNED','تحت التحرير'),
    ('REVIEWED','تمت مراجعته'),
    ('FINAL_REVIEWED','تمت المراجعة النهائية'),
    ('WITH_REVIEWER','عند المراجعين'),
    # ('APOLOGIZED','معتذر'),
    ('ONLINE','منشور'),
    ('EDITORIAL','افتتاحية'),
    ('ARCHIVED','مؤرشف'),
)

ARTICLE_TYPE = (
    ('VIDEO','video'),
    ('AUDIO','audio'),
    ('IMAGE','image'),
    ('TEXT','text'),
)

ARTICLE_FIELD_EN = (
    ('HEALTH','health'),
    ('IT','Information Technology'),
    ('ECOLOGY','Ecology'),
    ('ORGANISMS','Organisms'),
    ('NATURE','Nature and the universe'),
    ('CHEMICAL','Chemicals'),
    ('MATH','Math'),
    ('ENGINEERING','Engineering')
)

ARTICLE_FIELD_AR = (
    ('HEALTH','الصحة'),
    ('IT','تقنية المعلومات'),
    ('ECOLOGY','البيئة'),
    ('ORGANISMS','الحياة'),
    ('NATURE','الكون و الطبيعة'),
    ('CHEMICAL','الكيميائيات'),
    ('MATH','الرياضيات'),
    ('ENGINEERING','هندسيات')
)

DECISION = (
    ('ACCEPT','accept'),
    ('REJECT','reject')
)

REVIEW_DECISION = (
    ('ACCEPT','accept'),
    ('APOLOGIZE','apologize'),
)



class User(models.Model):

    user_ID = models.BigAutoField(primary_key=True)
    first_name = models.CharField(max_length = 15)
    last_name = models.CharField(max_length = 15)
    birthdate = models.DateField(auto_now = False,auto_now_add = False)
    gender_en = models.CharField(max_length = 6, choices = GENDER_EN)
    gender_ar = models.CharField(max_length = 6, choices = GENDER_AR)
    email = models.EmailField(max_length = 40, unique=True)
    phone_number = models.BigIntegerField()
    country = models.CharField(max_length = 30)
    city = models.CharField(max_length = 20)
    activation = models.CharField(max_length=10, blank = True, null = True)
    
    class Meta:
        verbose_name_plural = 'User'
    
    def __str__(self):
        return '%i : %s %s' % (self.user_ID, self.first_name, self.last_name)

    # def get_absolute_url(self):
    #     return reverse(" `namespace`:urlname", kwargs={"pk": self.pk})
    

#-----------------------------------------------------------------------------------------#

class EBM (models.Model):

    EBM_ID = models.ForeignKey(
        'User',
        on_delete = models.CASCADE
    )
    password = models.CharField(max_length = 256)
    specialty_en = models.CharField(max_length = 20, choices = ARTICLE_FIELD_EN)
    specialty_ar = models.CharField(max_length = 20, choices = ARTICLE_FIELD_AR)
    account_status_en = models.CharField(max_length = 7, choices = ACCOUNT_STATUS_EN)
    account_status_ar = models.CharField(max_length = 7, choices = ACCOUNT_STATUS_AR)

    class Meta:
        verbose_name_plural = 'Editorial Board Member'
                 
    def __str__(self):
        return str(self.EBM_ID)

    def verify_password(self, raw_password):
        return pbkdf2_sha256.verify(raw_password, self.password)
        
    # def get_absolute_url(self):
    #     return reverse(" `namespace`:urlname", kwargs={"pk": self.pk})

#-----------------------------------------------------------------------------------------#

class Reviewer(models.Model):

    reviewer_ID = models.ForeignKey(
        'User',
        on_delete = models.CASCADE
    )
    password = models.CharField(max_length = 256)
    specialty_en = models.CharField(max_length = 20, choices = ARTICLE_FIELD_EN)
    specialty_ar = models.CharField(max_length = 20, choices = ARTICLE_FIELD_AR)
    workplace = models.CharField(max_length = 50)
    account_status_en = models.CharField(max_length = 7, choices = ACCOUNT_STATUS_EN)
    account_status_ar = models.CharField(max_length = 7, choices = ACCOUNT_STATUS_AR)
    
    class Meta:
        verbose_name_plural = 'Reviewer'
                
    def __str__(self):
        return str(self.reviewer_ID)
        
    def verify_password(self, raw_password):
        return pbkdf2_sha256.verify(raw_password, self.password)
        
    # def get_absolute_url(self):
    #     return reverse(" `namespace`:urlname", kwargs={"pk": self.pk})

#-----------------------------------------------------------------------------------------#

class Associate_Editor(models.Model):

    AE_ID = models.ForeignKey(
        "EBM",
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name_plural = 'Associate Editor'

    def __str__(self):
        return str(self.AE_ID)
    
        
    # def get_absolute_url(self):
    #     return reverse(" `namespace`:urlname", kwargs={"pk": self.pk})

#-----------------------------------------------------------------------------------------#

class Editor_in_Chief(models.Model):

    EIC_ID = models.ForeignKey(
        "EBM",
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name_plural = 'Editor in Chief'

    def __str__(self):
        return str(self.EIC_ID)

    # def get_absolute_url(self):
    #     return reverse(" `namespace`:urlname", kwargs={"pk": self.pk})

#-----------------------------------------------------------------------------------------#

# class Guest(models.Model):

#     Guest_ID = models.ForeignKey(
#         "User",
#         on_delete=models.CASCADE
#     )
#     special_number = models.BigIntegerField()

#     class Meta:
#         verbose_name_plural = 'Guest'
        
#     def __str__(self):
#         return str(self.Guest_ID)

    # def get_absolute_url(self):
    #     return reverse(" `namespace`:urlname", kwargs={"pk": self.pk})

#-----------------------------------------------------------------------------------------#

class Subscriber(models.Model):

    subscriber_ID = models.ForeignKey(
        'User',
        on_delete = models.CASCADE
    )
    password = models.CharField(max_length = 256)
    picture = models.ImageField(upload_to='writer_&_subscribers_pic/%Y/%m/%d')

    class Meta:
        verbose_name_plural = 'Subscriber'

    def __str__(self):
        return str(self.subscriber_ID)
        
    def verify_password(self, raw_password):
        return pbkdf2_sha256.verify(raw_password, self.password)
        
    # def get_absolute_url(self):
    #     return reverse(" `namespace`:urlname", kwargs={"pk": self.pk})

#-----------------------------------------------------------------------------------------#

class Admin(models.Model):

    admin_ID = models.ForeignKey(
        'User',
        on_delete = models.CASCADE
    )
    password = models.CharField(max_length=256)

    class Meta:
        verbose_name_plural = 'Admin'

    def __str__(self):
        return str(self.admin_ID)
    
    def verify_password(self, raw_password):
        return pbkdf2_sha256.verify(raw_password, self.password)
        
        
    # def get_absolute_url(self):
    #     return reverse(" `namespace`:urlname", kwargs={"pk": self.pk})

#-----------------------------------------------------------------------------------------#

class Setting(models.Model):

    article_price = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, verbose_name='article price(S.R.)')
    online_duration = models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='online duration(days)')
    editorial_duration = models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='editorial duration(days)')


    class Meta:
        verbose_name_plural = 'Setting'

    # def get_absolute_url(self):
    #     return reverse(" `namespace`:urlname", kwargs={"pk": self.pk})

#-----------------------------------------------------------------------------------------#

class Writer(models.Model):

    writer_ID = models.ForeignKey("User", on_delete=models.CASCADE)
    password = models.CharField(max_length = 256)
    specialty_en = models.CharField(max_length = 20, choices = ARTICLE_FIELD_EN)
    specialty_ar = models.CharField(max_length = 20, choices = ARTICLE_FIELD_AR)
    workplace = models.CharField(max_length = 50)
    account_status_en = models.CharField(max_length = 7, choices = ACCOUNT_STATUS_EN, default='FREEZE')
    account_status_ar = models.CharField(max_length = 7, choices = ACCOUNT_STATUS_AR, default='FREEZE')
    picture = models.ImageField(upload_to='writer_&_subscribers_pic/%Y/%m/%d')

    class Meta:
        verbose_name_plural = ("Wirter")
                
    def __str__(self):
        return str(self.writer_ID)
        
    def verify_password(self, raw_password):
        return pbkdf2_sha256.verify(raw_password, self.password)
        
    # def get_absolute_url(self):
    #     return reverse(" `namespace`:urlname", kwargs={"pk": self.pk})

#-----------------------------------------------------------------------------------------#
 
# class Credit_Card(models.Model):

#     credit_card_ID = models.BigAutoField(primary_key=True)
#     user_ID = models.ForeignKey("User", on_delete=models.CASCADE)

scientificJournalism/templates/scientificJournalism/body_component/archive.html
{% extends extend_page %}


{% block body %}
    <div class="content">
        <div class="container">
            <div class="section text_post_block">
                <h2 class="section_title section_title_big">{{ archive }}</h2>
                <p>{{ about_archive }}</p>
            </div>

            <div class="section">
                <h2 class="section_title section_title_big"> {{ search_in_archive }} </h2>
                <form class="search" method="POST" action="{% url 'archive_search' %}">
                    {% csrf_token %}
                    <input type="text" name="archive_key_word" placeholder="{{ search }}" id="key_word" style="border:1px solid #1f74ad">
                    <button class="" type="submit"><i class="fa fa-search"></i></button>
                </form>
            </div>

            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <div class="section">
                        <h3 class="section_title">{{ latest_articles }}</h3>
                        <ul class="circle_list">
                            
                            {% for article in latest_10_archived_articles %}
                                
                                {% if request.session.lang == 'ar' %}
                                    <li><h4><a href="{% url 'show_archived_article' article.article_ID %}">{{ article.title_ar }}</a></h4></li>
                                {% elif request.session.lang == 'en' %}
                                    <li><h4><a href="{% url 'show_archived_article' article.article_ID %}">{{ article.title_en }}</a></h4></li>
                                {% endif %}
                                    
                            {% endfor %}

                        </ul>
                    </div> 
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <div class="section">
                        <h3 class="section_title">{{ most_read_articles }}</h3>
                        <ul class="circle_list">

                            {% for article in most_10_archived_articles_read %}
                            
                                {% if request.session.lang == 'ar' %}
                                    <li><h4><a href="{% url 'show_archived_article' article.article_ID %}">{{ article.title_ar }}</a></h4></li>
                                {% elif request.session.lang == 'en' %}
                                    <li><h4><a href="{% url 'show_archived_article' article.article_ID %}">{{ article.title_en }}</a></h4></li>
                                {% endif %}
                                    
                            {% endfor %}

                        </ul>
                    </div>  
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <div class="section">
                        <h3 class="section_title">{{ most_rated_articles }}</h3>
                        <ul class="circle_list">

                            {% for article in highest_10_archived_articles_rate %}
                                    
                                {% if request.session.lang == 'ar' %}
                                    <li><h4><a href="{% url 'show_archived_article' article.article.article_ID %}">{{ article.article.title_ar }} ({{ article.rate }})</a></h4></li>
                                {% elif request.session.lang == 'en' %}
                                    <li><h4><a href="{% url 'show_archived_article' article.article.article_ID %}">{{ article.article.title_en }} ({{ article.rate }})</a></h4></li>
                                {% endif %}
                                    
                            {% endfor %}

                        </ul>
                    </div>  
                </div>
            </div>
            <br>
            <div class="row">                
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <div class="section">
                        <h3 class="section_title">{{ fields }}</h3>
                        <ul class="circle_list">
                                
                            <li><h4><a href="{% url 'get_archived_field_articles' num_archived_articles_in_fields.0.field %}">{{ health }} ({{ num_archived_articles_in_fields.0.num_of_articles }})</a></h4></li>
                            <li><h4><a href="{% url 'get_archived_field_articles' num_archived_articles_in_fields.1.field %}">{{ IT }} ({{ num_archived_articles_in_fields.1.num_of_articles }})</a></h4></li>
                            <li><h4><a href="{% url 'get_archived_field_articles' num_archived_articles_in_fields.2.field %}">{{ ecology }} ({{ num_archived_articles_in_fields.2.num_of_articles }})</a></h4></li>
                            <li><h4><a href="{% url 'get_archived_field_articles' num_archived_articles_in_fields.3.field %}">{{ organisms }} ({{ num_archived_articles_in_fields.3.num_of_articles }})</a></h4></li>
                            <li><h4><a href="{% url 'get_archived_field_articles' num_archived_articles_in_fields.4.field %}">{{ nature }} ({{ num_archived_articles_in_fields.4.num_of_articles }})</a></h4></li>
                            <li><h4><a href="{% url 'get_archived_field_articles' num_archived_articles_in_fields.5.field %}">{{ chemicals }} ({{ num_archived_articles_in_fields.5.num_of_articles }})</a></h4></li>
                            <li><h4><a href="{% url 'get_archived_field_articles' num_archived_articles_in_fields.6.field %}">{{ math }} ({{ num_archived_articles_in_fields.6.num_of_articles }})</a></h4></li>
                            <li><h4><a href="{% url 'get_archived_field_articles' num_archived_articles_in_fields.7.field %}">{{ engineering }} ({{ num_archived_articles_in_fields.7.num_of_articles }})</a></h4></li>

                        </ul>
                    </div> 
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <div class="section">
                        <h3 class="section_title">{{ authors }}</h3>
                        <ul class="circle_list">
                            
                            {% for writer in highest_writer_wrote_article %}
                                <li><h4><a href="#">{{ writer.name}} ({{ writer.num_articles }})</a></h4></li>
                            {% endfor %}
                                
                            
                            
                        </ul>
                    </div>   
                </div>
            </div>
        </div>
    </div>
{% endblock body %}
    

scientificJournalism/templates/scientificJournalism/body_component/archive_article.html
{% extends extend %}

{% load static %}

{% load tz %}

{% block body %}

        <!--==============================content================================-->
        <div class="content">
            <div class="container">
                <div class="row flex_reversed">
                    <div class="col-lg-2 col-md-1 col-sm-12">
                    </div>
                    <div class="col-lg-8 col-md-10 col-sm-12">
                        <div class="section">
                            
                            <div class="clearfix page_theme">
                                <div class="f_left">
                                    <div class="post_image_buttons">
                                        <div class="buttons_container">
                                            <a href="#" class="button banner_button travel">
                                                {% if request.session.lang == 'ar' %}
                                                    {{ article.get_field_ar_display }}
                                                {% else %}
                                                    {{ article.get_field_en_display }}
                                                {% endif %}
                                            </a>
                                        </div>
                                    </div>
                                    <div class="event_date" style="color:black">{{ article.publishing_date|timezone:'Asia/Riyadh' }}</div>
                                </div>
                                <div class="f_right event_info">
                                    
                                    <i class="fa fa-comments-o d_inline_m m_right_3"></i> 
                                    <span>{{ comment|length }} </span>
                                    <span style="padding:0 4px">|</span>
                                    <i class="fa fa fa-star-o d_inline_m m_right_3"></i> 
                                    <span>
                                        {% if not average.subscriber_rating__avg %}
                                            0
                                        {% else %}
                                            {{ average.subscriber_rating__avg }}
                                        {% endif %}
                                    </span>
                                    <span style="padding:0 4px">|</span>
                                    <i class="fa fa-eye d_inline_m m_right_3"></i> 
                                    <span>{{ article.number_of_views }}</span>
                                    
                                </div>
                            </div>
        
                            <h2 class="section_title section_title_medium_var2">
                                {% if request.session.lang == 'ar' %}
                                    {{ article.title_ar }}
                                {% else %}
                                    {{ article.title_en }}
                                {% endif %}
                            </h2>
                            <div class="text_post_block">
                                <div class="scale_image_container">
                                    <a href="#"><img src="{{ article.cover_image.url }}" alt="Cover Image" class="scale_image" width="750" height="375"></a>
                                </div>
                                <p>
                                    {% if request.session.lang == 'ar' %}
                                        {{ article.brief_of_article_ar }}
                                    {% else %}
                                        {{ article.brief_of_article_en }}
                                    {% endif %}
                                </p>
                            </div>

                            <br>
                           
                            <div class="text_post_block">
                                <h3 class="section_title section_title_small"></h3>
                                <p>
                                    {% if request.session.lang == 'ar' %}
                                        {{ article.context_ar|safe }}
                                    {% else %}
                                        {{ article.context_en|safe }}
                                    {% endif %}
                                </p>
                                
                                {% for media in multimedia %}
                                    
                                    {% if media.get_format_display == 'image' %}
                                        <img src="{{ media.content.url }}" alt="" class="full_article_image" width="750" height="375">
                                        <br/><br/>
                                    {% elif media.get_format_display == 'audio' %}
                                        <audio controls controlsList="nodownload" style="width:100%">
                                            <source src="{{ media.content.url }}" type="audio/mpeg">
                                            Your browser does not support the audio element.
                                        </audio>
                                        <br/><br/>
                                    {% else %}
                                        <video width="100%" controls>
                                            <source src="{{ media.content.url }}" type="video/mp4">
                                            Your browser does not support the video tag.
                                        </video>
                                        <br/><br/>
                                    {% endif %}
                                        
                                        
                                {% endfor %}
                                    
                            </div>
                                
                            <div class="section">
                                <h2 class="section_title">{{ about_writer }}</h2>
                
                                <div class="row">
                                    <div class="col-lg-3 col-md-3 col-sm-3 f_left">
                                        <img src="{{ writer_information.picture.url }}" alt="" height="165" width="165">
                                    </div>
                                    <div class="col-lg-9 col-md-9 col-sm-9">
                                        <table class="table_type_1">
                                            <tbody>
                                                <tr class="f_size_large">
                                                    <th colspan="2">{{ writer_info }}</th>
                                                </tr>
                                                <tr>
                                                    <td>{{writer_information.writer_ID.first_name|add:' '|add:writer_information.writer_ID.last_name}}</td>
                                                    <td>{{writer_information.writer_ID.email}}</td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        {% if request.session.lang == 'ar' %}
                                                            {{writer_information.get_specialty_ar_display}}
                                                        {% else %}
                                                            {{writer_information.get_specialty_en_display}}
                                                        {% endif %}
                                                    </td>
                                                    <td>{{writer_information.writer_ID.country}}</td>
                                                </tr>
                                                <tr>
                                                    <td>{{writer_information.workplace}}</td>
                                                    <td>{{writer_information.writer_ID.city}}</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
            
                            <div class="section">
                                <h2 class="section_title">{{ comments_header }}</h2>
                                <ul class="comments">
                                
                                {% if comment %}
                                    {% for comment in comments %}
                                        <li>
                                            <div class="comment clearfix">
                                                <div>
                                                    <div><img src="{{ comment.subscriber_ID.picture.url }}" alt="" width="80" height="80"></div>
                                                </div>
                                                <div>
                                                    <div class="clearfix">
                                                        <a href="#"><h5 class="f_left">{{comment.subscriber_ID.subscriber_ID.first_name|add:' '|add:comment.subscriber_ID.subscriber_ID..last_name}}</h5></a>
                                                        <div class="event_date f_right">{{ comment.comment_date }}</div>
                                                    </div>
                                                    <p>{{ comment.comment_content }}</p>
                                                </div>
                                            </div>
                                        </li>
                                    {% endfor %}     
                                {% else %}
                                    <h2 class="center">{{ no_comments }}</h2>
                                {% endif %}
                                        
                                </ul>
                            </div>
                                                        
                        </div>        
                    </div>
                    <div class="col-lg-2 col-md-1 col-sm-12">
                    </div>
                </div>
            </div>
        </div>
      
      
       
    

{% endblock body %}
    


{% block script %}

{% endblock script %}